project_name: ServerStatuc-Client
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    id: "ServerStatus-Client"
    dir: .
    main: ./cmd/clinet